# Generated by Django 4.2.30 on 2026-09-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(help_text='17-character Vehicle Identification Number', max_length=17, unique=True, verbose_name='VIN')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='License Plate')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Model Year')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Operational'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', help_text='Current operational state of the vehicle', max_length=20)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=20)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Latest recorded odometer reading in kilometers', verbose_name='Current Odometer (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('start_odometer', models.PositiveIntegerField(verbose_name='Start Odometer (km)')),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Odometer (km)')),
                ('distance_km', models.PositiveIntegerField(default=0, help_text='Calculated in Python save() in Django 4.2 (migrates to GeneratedField in Django 5.0)', verbose_name='Distance (km)')),
                ('fuel_liters', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Fuel Purchased (Liters)')),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Fuel Cost ($)')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Trip Purpose / Route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Trip Log',
                'verbose_name_plural': 'Trip Logs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inspection Date & Time')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='Odometer at Inspection (km)')),
                ('brakes_passed', models.BooleanField(default=True, verbose_name='Brakes Passed')),
                ('tires_passed', models.BooleanField(default=True, verbose_name='Tires Passed')),
                ('lights_passed', models.BooleanField(default=True, verbose_name='Lights & Signals Passed')),
                ('fluids_passed', models.BooleanField(default=True, verbose_name='Fluids Checked')),
                ('overall_passed', models.BooleanField(default=True, verbose_name='Overall Safety Passed')),
                ('notes', models.TextField(blank=True, verbose_name='Inspector Notes')),
                ('document', models.FileField(blank=True, help_text='Upload signed inspection sheet or checklist image', null=True, upload_to='inspections/%Y/%m/', verbose_name='Inspection Photo / Sheet')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('OIL_CHANGE', 'Oil & Filter Change'), ('TIRE_ROTATION', 'Tire Rotation & Alignment'), ('BRAKE_SERVICE', 'Brake Pad & Rotor Service'), ('TRANSMISSION', 'Transmission Fluid Flush'), ('ANNUAL_INSPECTION', 'Annual Safety Certification')], max_length=50, verbose_name='Service Code')),
                ('description', models.TextField(blank=True, verbose_name='Notes & Specifications')),
                ('interval_km', models.PositiveIntegerField(default=10000, help_text='Required maintenance interval in kilometers', verbose_name='Interval (km)')),
                ('last_service_odometer', models.PositiveIntegerField(default=0, verbose_name='Last Serviced At (km)')),
                ('last_service_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last Serviced Date')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['vehicle', 'service_code'],
                'unique_together': {('vehicle', 'service_code')},
            },
        ),
    ]
