# Generated by Django 4.2.30 on 2026-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenanceschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='inspections/%Y/%m/', verbose_name='Inspection Photo / Sheet'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='interval_km',
            field=models.PositiveIntegerField(default=10000, verbose_name='Interval (km)'),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='distance_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='fuel_liters',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Fuel (L)'),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, verbose_name='Trip Purpose'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Odometer (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active & Operational'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='17-character VIN', max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['vehicle', '-start_time'], name='idx_trip_veh_start'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'fuel_type'], name='idx_vehicle_status_fuel'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.UniqueConstraint(fields=('vehicle', 'service_code'), name='uniq_veh_service_code'),
        ),
        migrations.AddConstraint(
            model_name='triplog',
            constraint=models.CheckConstraint(check=models.Q(('end_odometer__isnull', True), ('end_odometer__gte', models.F('start_odometer')), _connector='OR'), name='check_trip_end_gte_start'),
        ),
    ]
