# Generated by Django 4.2.30 on 2026-09-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_alter_maintenanceschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.CharField(choices=[('ACTIVE', 'Active & Operational'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low — Cosmetic / Non-Urgent'), ('MEDIUM', 'Medium — Scheduled Interval'), ('HIGH', 'High — Performance Issue'), ('CRITICAL', 'Critical — Safety Defect (Brakes, Tires)')], default='MEDIUM', max_length=20)),
                ('reason', models.TextField(verbose_name='Operational Reason / Observed Defect')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('AI_APPROVED', 'Auto-Approved by AI Agent'), ('ADMIN_APPROVED', 'Approved by Staff Admin'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('decision_notes', models.TextField(blank=True, default='', verbose_name='Decision Rationale')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_status_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_status_changes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_requests', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Status Change Request',
                'verbose_name_plural': 'Status Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
